# Generated by Django 3.2.8 on 2021-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shope', '0005_auto_20211013_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('orderId',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='cloth',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(default='deafult cloth', max_length=32),
            preserve_default=False,
        ),
    ]
