# Generated by Django 3.2.8 on 2021-10-15 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shope', '0006_auto_20211015_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesproduct',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
