# Generated by Django 3.2.8 on 2021-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shope', '0006_auto_20211015_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('orderId',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('orderId',), 'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображение продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_created=True, default='2000-01-01', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
