# Generated by Django 3.2.8 on 2021-10-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shope', '0007_favoritesproduct_user'),
        ('Shope', '0008_alter_product_created'),
    ]

    operations = [
    ]
