# Generated by Django 3.2.8 on 2021-10-16 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shope', '0009_merge_20211016_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='favoritesproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='favoritesproduct',
            name='product',
            field=models.ManyToManyField(to='Shope.Product'),
        ),
        migrations.AlterField(
            model_name='favoritesproduct',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
