# Generated by Django 3.2.8 on 2021-10-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shope', '0010_auto_20211016_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritesProduct',
        ),
    ]
