# Generated by Django 3.2.8 on 2021-10-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shope', '0012_auto_20211018_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
