# Generated by Django 3.2.8 on 2021-10-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shope', '0013_remove_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/uploads/%Y/%m/%d/')),
                ('orderId', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Shope.product')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображение продуктов',
                'ordering': ('orderId',),
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
